### ISSUE TITLE
Link with 2.1 version changes cannot open in github

### ISSUE THREAD

**Issue by batruji** [voxbone/voxapi-client-php#1]
Greetings,

About an hour ago I received an email leading to this topic:
https://groups.google.com/forum/#!topic/voxbonedevelopers/KCTcuP8Z3-Y

There is a link for the PHP Library 2.1 (New Release) which leads to this page:
https://github.com/voxbone/voxapi-client-php/releases/tag/v2.1

However the page shows an 404 error (I am logged into github).

**Comment by sachanacar** [comment]
Hi! Thanks for opening an issue! Indeed I see the link is broken, should be:

https://github.com/voxbone/voxapi-client-php/releases/tag/2.1

Cheers!
Sacha
