### ISSUE TITLE
Publishing `voxbone/voxapi-client-php` to packagist

### ISSUE THREAD

**Issue by kadryjanek** [voxbone/voxapi-client-php#3]
Could you please publish your `voxbone/voxapi-client-php` to https://packagist.org/ ?
`Packagist` is the default `Composer` (Dependency Manager for PHP ) package repository.

After publishing your client to `Packagist` you can configure and enable `Packagist` service hook on `GitHub` to ensure that package is always up to date:  https://packagist.org/about

This will allow for defining `voxbone/voxapi-client-php` dependency in `composer.json` and installing it using just `Composer` (no more manual downloading will be necessary).

**Comment by sachanacar** [comment]
Thanks @kadryjanek ! The library has been [published on packagist ](https://packagist.org/packages/voxbone/voxapi-client-php). Hook to be implemented shortly.

Cheers!
Sacha
